### PR TITLE
Fix Issue #156

### LINKED ISSUE #156: Crash if folder name contains some special characters
I have found `xcake` to crash if, among the files that I have defined to be include in the project, there is a folder which contains either a dash (`-`) or a dot (`.`) in its name. This should work because those characters are allowed in Xcode groups' names.

This is the error message:

```
/Users/frankdilo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcake-0.8.8/lib/xcake/xcode/project.rb:118:in `file_reference_for_path': undefined method `dirname' for #<Xcodeproj::Project::Object::PBXFileReference:0x007ff1ed931b60> (NoMethodError)
	from /Users/frankdilo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcake-0.8.8/lib/xcake/context/xcodeproj_context.rb:56:in `file_reference_for_path'
	from /Users/frankdilo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcake-0.8.8/lib/xcake/generator/target_file_reference_generator.rb:33:in `include_file_for_path_and_target'
	from /Users/frankdilo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcake-0.8.8/lib/xcake/generator/target_file_reference_generator.rb:26:in `block in visit_target'
	from /Users/frankdilo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcake-0.8.8/lib/xcake/generator/target_file_reference_generator.rb:25:in `each'
	from /Users/frankdilo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcake-0.8.8/lib/xcake/generator/target_file_reference_generator.rb:25:in `visit_target'
	from /Users/frankdilo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcake-0.8.8/lib/xcake/visitor.rb:45:in `visit'
	from /Users/frankdilo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcake-0.8.8/lib/xcake/dsl/project.rb:83:in `block in accept'
	from /Users/frankdilo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcake-0.8.8/lib/xcake/dsl/project.rb:82:in `each'
	from /Users/frankdilo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcake-0.8.8/lib/xcake/dsl/project.rb:82:in `accept'
	from /Users/frankdilo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcake-0.8.8/lib/xcake/command/make.rb:25:in `block in run'
	from /Users/frankdilo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcake-0.8.8/lib/xcake/command/make.rb:23:in `each'
	from /Users/frankdilo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcake-0.8.8/lib/xcake/command/make.rb:23:in `run'
	from /Users/frankdilo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
	from /Users/frankdilo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcake-0.8.8/bin/xcake:6:in `<top (required)>'
	from /Users/frankdilo/.rbenv/versions/2.2.2/bin/xcake:23:in `load'
	from /Users/frankdilo/.rbenv/versions/2.2.2/bin/xcake:23:in `<main>'
```

### PR DESCRIPTION
**Pull request by asifmohd**
Having . or - in folder names would crash xcake

This PR fixes it by checking if the file which needs to be added to a target is a directory or a file.
If it's a directory we skip over it.

This fixes #156

### CODE REVIEW

File: spec/generator/target_file_reference_generator_spec.rb [hunk 1]
```diff
@@ -67,6 +67,27 @@ module Xcake
       @generator.visit_target(@target)
     end
 
+    it "should ingore directories" do
```
Comment (jcampbell05) [inline spec/generator/target_file_reference_generator_spec.rb]: just a small typo here :)

**Comment by jcampbell05** [comment]
Thanks, looks great. If you could fix that typo :)

**Comment by asifmohd** [comment]
@jcampbell05 done :)

**Comment by jcampbell05** [comment]
Thanks @asifmohd
